// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5Vz0f30IolVJ1HgZmYpi2_520LpS3wk',
    appId: '1:407779072714:web:88c37dd504f66ed0ae3233',
    messagingSenderId: '407779072714',
    projectId: 'onceprac-c903f',
    authDomain: 'onceprac-c903f.firebaseapp.com',
    storageBucket: 'onceprac-c903f.firebasestorage.app',
    measurementId: 'G-M7NEYJRTQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8UTlYu9A-9xfcMnvn8M8eHUMMoAGHoDg',
    appId: '1:407779072714:android:4536188e136f6603ae3233',
    messagingSenderId: '407779072714',
    projectId: 'onceprac-c903f',
    storageBucket: 'onceprac-c903f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwCFBx-RwfiRAlXzB4osveWyz0Nm7duN0',
    appId: '1:407779072714:ios:98ca80cf2eda54c1ae3233',
    messagingSenderId: '407779072714',
    projectId: 'onceprac-c903f',
    storageBucket: 'onceprac-c903f.firebasestorage.app',
    iosBundleId: 'com.once.prac.onceprac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwCFBx-RwfiRAlXzB4osveWyz0Nm7duN0',
    appId: '1:407779072714:ios:98ca80cf2eda54c1ae3233',
    messagingSenderId: '407779072714',
    projectId: 'onceprac-c903f',
    storageBucket: 'onceprac-c903f.firebasestorage.app',
    iosBundleId: 'com.once.prac.onceprac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk5Vz0f30IolVJ1HgZmYpi2_520LpS3wk',
    appId: '1:407779072714:web:f1f7cbf856c0a791ae3233',
    messagingSenderId: '407779072714',
    projectId: 'onceprac-c903f',
    authDomain: 'onceprac-c903f.firebaseapp.com',
    storageBucket: 'onceprac-c903f.firebasestorage.app',
    measurementId: 'G-NSZNW8BQH7',
  );
}
